### ISSUE TITLE
Module missing

### ISSUE THREAD

**Issue by asif-rehan** [kaelzhang/tensorflow-2-DA-RNN#1]
Hi, thank you for providing the example notebook to show the use of the DA-RNN library! 

The `notebook.common` module imports the `get_rolling_window` module but this is not present in the repository. So `notebook/pytorch.ipynb` throws an error. Could this module be uploaded to the notebook folder?  Appreciate it and thank you!

`ModuleNotFoundError: No module named 'get_rolling_window'`

**Comment by kaelzhang** [comment]
You'd better run `make install` first, and `get-rolling-window` is located at [dev-requirements.txt](https://github.com/kaelzhang/DA-RNN-in-Tensorflow-2-and-PyTorch/blob/master/dev-requirements.txt)

**Comment by kaelzhang** [comment]
I suggest to use [anaconda](https://docs.anaconda.com/anaconda/install/) to manage environments
