### ISSUE TITLE
Question about the size of Y in DARNN code written in Keras

### ISSUE THREAD

**Issue by ghost** [kaelzhang/tensorflow-2-DA-RNN#6]
I have a question regarding the DARNN code written in Keras. 

In line 439 of model.py file (da_rnn/keras/model.py), Y is extracted from the inputs. 

However, using Y = inputs[:, :, -self.y_dim:], the size of Y becomes (batch_size, T, y_dim) instead of (batch_size, T - 1, y_dim). 

Could you please check this code?

**Comment by kaelzhang** [comment]
Sorry, this repo is only for research purpose. Actually, the performance of DARNN is really poor, so I did not spend too much time on it.

The keras implementation is buggy, but pytorch one works. You might as well check the pytorch implementation.

Don't use this model in production, it will lose money.

**Comment by ghost** [comment]
Thank you for replying to my question. 

I was also studying DARNN for the purpose of the study. 

I will check the pytorch version as well. 

Thank you again!
